### ISSUE TITLE
Stats page shows incorrect balance

### ISSUE THREAD

**Issue by grumpyfinance** [grumpyfinance/grumpy-swap#2]
**Bug Description**
A wallet with Grumpy tokens should show the amount of grumpy in their wallet once connected

**Steps to Reproduce**

1. Go to https://swap.grumpy.finance/#/stats
2. Click Connect Wallet

**Expected Behavior**
"Your $Grumpy Balance" section should reflect the amount of grumpy in the wallet

**Additional Context**
The "Your $Grumpy Balance" section is blank
![empty-balance](https://user-images.githubusercontent.com/81785683/124312494-693c9c80-db3d-11eb-9415-e2254615088e.png)
There are not any relevant JS errors on the page

**Comment by grumpyfinance** [comment]
@lumtwj we merged your PR: #1 but it doesn't seem to function as intended.
Would you mind following the steps outlined in this issue to see if you can recreate the issue? If you can, would you be able to submit a fix?

Thanks

**Comment by lumtwj** [comment]
I can't replicate the issues, it seems to be working fine for me.

![Screenshot 2021-07-03 at 9 06 25 AM](https://user-images.githubusercontent.com/340740/124339136-cd636d00-dbde-11eb-8e23-be0aa87b0c42.png)

Are you still having issue loading the information right now?

**Comment by grumpyfinance** [comment]
Yes. The issue still remains. Not sure what it's related to.

**Comment by grumpyfinance** [comment]
Looks like the issue is resolved. Cannot be recreated
